### ISSUE TITLE
Division by zero error when building a pMC from DRN

### ISSUE THREAD

**Issue by unsigned-decimal** [stormchecker/stormpy#20]
Good day,

I am receiving a division by zero error when I try to build a pMC model from a .drn file. I attached a zip file containing the python script that was used and the drn file that causes the error.
The script does the following:
1. Loads the POMDP maze file from the examples.
2. Builds the POMDP model with state valuations and choice labels
3. Makes the POMDP model canonical.
4. Unfolds memory into the POMDP model.
5. Makes the POMDP model simpel
6. Applies the FSC to obtain a pMC.
7. Writes the pMC to a drn file. 
8. Reads the pMC from the drn file.

The error occurs during the last step of the script. When trying to load the drn file into storm using the command line the same error occurs. I discovered that the cause of the error are the rational functions for some state transitions. An example, every state transition from state 29 had the following probability: 

1385722962267845/18014398509481984

When I manually adjusted it to: 

1385722962267845/180143985094819 

I could successfully load the model into storm. Is this a bug or am I doing something wrong in my script?

Additional information:
Storm version: 1.6.2
Stormpy version: 1.6.2
Carl version: 14.20
Pycarl version: 2.0.4
OS: Ubuntu 18.04.5 LTS
  
[test.zip](https://github.com/moves-rwth/stormpy/files/5602461/test.zip)

**Comment by tquatmann** [comment]
Thank you for pointing this out. Apparently, we silently converted 64Bit integers to 32 Bits which in your case (since the denominator is exactly 2^54) resultet in a division by 0.
I now fixed this. To use that fix, please check out the master branch of Storm. (You might also need the master branch of StormPy to ensure compatibility of Storm and StormPy).

Unfortunately, we are still not able to parse integer literals beyond 64 Bits but [we are working on this](https://github.com/moves-rwth/storm/issues/97). Note that the parsing will fail in case 64 Bits do not suffice, i.e., no silent truncations should happen.

**Comment by unsigned-decimal** [comment]
Hallo tquatmann,

I followed your advice and reinstalled storm and stormpy using the master branch. However the division by zero error still remains. Any ideas as to what is going wrong?

**Comment by tquatmann** [comment]
I accidently pushed my fix to the wrong branch (rookie mistake, I know...) and only fixed that yesterday. I think you have still been on an old commit before my fix. Please build the most recent version again. Sorry for the inconvenience.
